
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = 12397642-13da-4b76-a667-c449abb257a8

###
POST http://localhost:5105/Admins/Register
Content-Type: application/json

{
    "UserName": "fidel", 
    "Password": "Bla-Bla-123",
    "GymId": "{{gymId}}"
}

