
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json

@quibumaPt1 = 07b464b8-b1ec-4169-9dcd-87de90ccf3fc
@quibumaPt2 = ef092159-57de-42fc-832e-94874bf98096
@quibumaMaster1 = DEFCA9BD-4E21-4C2A-9848-3DE867206D2B

@fightMt1 = ef920f2a-e9b9-44d6-91c0-f638bb09e307
@fightMt2 = 6e9dc946-c313-4f62-832f-1c505825256f

@topFitnessPt1 = 6e9dc2bf-ea2a-45e6-8554-8e720eb414f1
@topFitnessPt2 =45aac776-5547-4b3e-9c16-04bec9965e0a

@adminId = 7d555faf-06b9-409f-a3ba-60d2a6bfc228

###
POST http://localhost:5105/Trainers
Content-Type: application/json

{
    "Name": "Quibuma-Pt1", 
    "Phone": "923001003",
    "Email": "quibumapt1@gmail.com",
    "Specialization": "Body Building",    
    "MemberId":"{{quibumaPt1}}"
}

