
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@adminId = 7D555FAF-06B9-409F-A3BA-60D2A6BFC228
@geovanyAdminId = 3effc5e5-bdd2-47f2-85fb-c185b4ac2144
@xagasAdminId = c0b29c46-1c76-4f01-adb3-38aea53424a0
@stiveAdminId = 1fc4aba1-aa06-4d61-84e0-eb9aa258b14f
@fidelAdminId = bb7868f0-cd9d-4ff5-9f2d-c08a0a38220e
@celsioAdminId = d905c0e3-779e-4797-a5bf-00c89ef9557b
###
POST http://localhost:5105/Trainers
Content-Type: application/json

{
    "Name": "Geovani Oliveira", 
    "Phone": "924003003",
    "Email": "enjetech.dev1@gmail.com",
    "Specialization": "Braziliam Jiu-Jitsu",    
    "AdminId":"{{geovanyAdminId}}"
}

