
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@trainerId = d3e7b917-5f02-47ae-b654-6a7fed195f11

###
DELETE  http://{{host}}/Trainers/{{trainerId}}
Content-Type: {{jsonContentType}}

