
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@trainerId = 8e89b6ef-881c-43f0-b17b-e075de1b6eb7

###
DELETE  http://{{host}}/Trainers/{{trainerId}}
Content-Type: {{jsonContentType}}

