
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@trainerId = 639e130f-b54d-420b-bcb4-dc448a6356f9

###
GET  http://{{host}}/Trainers/{{trainerId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Trainers/List
Content-Type: {{jsonContentType}}