
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@trainerId = 48e2e07c-4b8a-4c01-be87-e4c105c2d149

###
GET  http://{{host}}/Trainers/{{trainerId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Trainers/List
Content-Type: {{jsonContentType}}