
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@memberId = e4ef77f1-4c36-4c64-a61d-eb9d73ff9f2b
@memberId2 = 258FC6AD-90E7-44A6-8F4F-DE3E98355404

@gymIdQuibuma = 38139b2e-e867-4446-9ddb-2d7b673ade27	
@gymIdFightSociety = 3dd38597-65f5-40be-8d7a-6b6bed350b9d	
@gymZ1 = e7f2d4bf-b428-433a-bd41-9d824923c9bb
@topFitnessGym = 62af57ad-0e94-4cc4-888b-7a415803271a

###
GET  http://{{host}}/Members/{{memberId}}
Content-Type: {{jsonContentType}}


###
GET  http://{{host}}/Members/List
Content-Type: {{jsonContentType}}


###
GET  http://{{host}}/Members/List/{{gymIdFightSociety}}
Content-Type: {{jsonContentType}}


###
GET  http://{{host}}/Members/{{memberId2}}/Subscriptions
Content-Type: {{jsonContentType}}
