
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@member1Quibuma = abce4882-6535-4308-86c5-7b5ed2570a13
@member2Quibuma = 2c46acb6-c673-4978-861b-f1c8f98db733

###
POST http://localhost:5105/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Basic", 
    "MemberId": "{{member1Quibuma}}"
}

###
POST http://{{host}}/Subscriptions
Content-Type: {{jsonContentType}}

{
    "SubscriptionType": "Basic", 
    "MemberId": "258fc6ad-90e7-44a6-8f4f-de3e98355404"
}
