
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@subscriptionId = 8612B4B5-C96E-4966-A47A-5DADAC72ED0E

###
DELETE  http://{{host}}/Subscriptions/{{subscriptionId}}
Content-Type: {{jsonContentType}}

