
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@subscriptionId = 06a19606-09e1-4690-a79b-0ba1ef80b17f

###
DELETE  http://{{host}}/Subscriptions/{{subscriptionId}}
Content-Type: {{jsonContentType}}

