
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@adminId = 7D555FAF-06B9-409F-A3BA-60D2A6BFC228
@subscriptionId = 
###
GET  http://{{host}}/Subscriptions/{{subscriptionId}}
Content-Type: {{jsonContentType}}

