
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@subscriptionId1 = 19a3e3cb-d4fb-4814-ac34-26c45bce6412 
@subscriptionId2 = 02992F15-C972-4F33-9F6E-6633420EB17E


###
GET  http://{{host}}/Subscriptions/c6f7ebf2-8586-4e56-a785-fa5fc4a42e80
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Subscriptions/{{subscriptionId2}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Subscriptions/List
Content-Type: {{jsonContentType}}