
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json

@gymIdQuibuma = 38139b2e-e867-4446-9ddb-2d7b673ade27	
@gymIdFightSociety = 3dd38597-65f5-40be-8d7a-6b6bed350b9d	
@gymZ1 = e7f2d4bf-b428-433a-bd41-9d824923c9bb
@topFitnessGym = 740d338b-a8b7-4e2d-8ccb-65ee1ae778ca

@subscriptionId1 = f958a02f-6d3f-4ffb-af85-d803276c7c80
@subscriptionId2 = 7c0406b6-e440-4675-8f70-6dc28c14c0d7


###
GET  http://{{host}}/Subscriptions/{{subscriptionId2}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Subscriptions/{{subscriptionId1}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Subscriptions/List
Content-Type: {{jsonContentType}}
