
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@subscriptionId = 02992f15-c972-4f33-9f6e-6633420eb17e
@subscriptionId2 = 06a19606-09e1-4690-a79b-0ba1ef80b17f

@quibumaBodyRoomId = 40A171F7-5230-4474-B49F-9CF25A50C9E0
@quibumaKickRoomId = 1a5b1dd9-43e0-4451-845f-3ceae5e5cb43

@JudoRoomId = CF9D6AA7-2611-4012-A004-C2E52FF63853


###
PUT http://{{host}}/Subscriptions/{{subscriptionId}}
Content-Type: {{jsonContentType}}

{
    "SubscriptionType": "Plus"
}


###
DELETE  http://{{host}}/Subscriptions/f2457b98-f25e-4caf-b017-eb26dab1b7a4
Content-Type: {{jsonContentType}}


    "SubscriptionType": "Premium"
}


###
DELETE  http://{{host}}/Subscriptions/f2457b98-f25e-4caf-b017-eb26dab1b7a4
Content-Type: {{jsonContentType}}

