
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@adminId = 7D555FAF-06B9-409F-A3BA-60D2A6BFC228

@gymIdQuibuma = da078937-8cde-4218-b248-96feb7c14f7e
@gymIdFightSociety = 89a0f40a-6a7e-47a0-a355-c8904fce2df7
@gymZ1 = bfce5f1e-2d69-4801-8ade-2c77ecf61595
@topFitnessGym =12397642-13da-4b76-a667-c449abb257a8

###
POST http://localhost:5105/Rooms
Content-Type: application/json

{
    "Name": "KickBoxing", 
    "Capacity": 25,
    "GymId": "{{gymIdQuibuma}}"
}

###
POST http://localhost:5105/Rooms
Content-Type: application/json

{
    "Name": "Yoga", 
    "Capacity": 30,
    "GymId": "{{topFitnessGym}}"
}