
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@roomId = 528a1a02-be51-452d-a24e-e388a47b0512

###
DELETE  http://{{host}}/Rooms/{{roomId}}
Content-Type: {{jsonContentType}}

