
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@roomId = 41f00c4b-1b38-41ec-a7a0-1ce5ed644c4c

@gymIdQuibuma = 38139b2e-e867-4446-9ddb-2d7b673ade27	
@gymIdFightSociety = 3dd38597-65f5-40be-8d7a-6b6bed350b9d	
@gymZ1 = e7f2d4bf-b428-433a-bd41-9d824923c9bb
@topFitnessGym = 740d338b-a8b7-4e2d-8ccb-65ee1ae778ca


###
GET  http://{{host}}/Rooms/{{roomId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Rooms/List
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Rooms/40a171f7-5230-4474-b49f-9cf25a50c9e0/Sessions
Content-Type: {{jsonContentType}}
