
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@roomId = d1093172-f63f-476b-a8b4-89e7f066210c

###
GET  http://{{host}}/Rooms/{{roomId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Rooms/List
Content-Type: {{jsonContentType}}