
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = E373C45C-7628-458E-BDFC-93BA58F81037

###
DELETE  http://{{host}}/Gyms/{{gymId}}
Content-Type: {{jsonContentType}}

