
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = f2f49541-af5a-454e-8c32-5dd6fed9637f

###
DELETE  http://{{host}}/Gyms/{{gymId}}
Content-Type: {{jsonContentType}}

