
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = e7f2d4bf-b428-433a-bd41-9d824923c9bb

###
GET  http://{{host}}/Gyms/{{gymId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Gyms/List
Content-Type: {{jsonContentType}}