
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = 221bb04b-1f47-4d91-a148-582f3f59bc8

###
GET  http://{{host}}/Gyms/{{gymId}}
Content-Type: {{jsonContentType}}

###
GET  http://{{host}}/Gyms/List
Content-Type: {{jsonContentType}}