
@hostname = localhost
@port = 5105
@host = {{hostname}}:{{port}}
@jsonContentType = application/json
@gymId = 38139b2e-e867-4446-9ddb-2d7b673ade27

###
PUT http://{{host}}/Gyms/{{gymId}}
Content-Type: {{jsonContentType}}

{
    "name": "Quibuma Sports",
    "address": "Morro Bento, Luanda"
}
